# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneBook2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneBook2
pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

end
